# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 788aa0bc20d7cc9f90451c49af6f46ab3726e7c0a226613d1b820e9e3150bbeaa022153ed168968d0a52290eab82816bf58d8285f6f09956461a103069b316fc

test:
  secret_key_base: 60667aa74834f352b0802b68c7f06145ce6493741a9bc7e7d2bffdc6a69220ead0632c146f4b3c6b2181580de6412da09fba2e3e43e1d8d06ec4ea80d5dae8fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
